[package]
name = "richard/env"
version = "0.0.1"
description = "show a list of environment variables"
readme = "README.md"
repository = "https://github.com/richardanaya/env"

[[module]]
name = "env"
source = "env.wasm"
abi = "wasi"

[[command]]
name = "env"
module = "env"